# -*- coding: utf-8 -*-
"""utils/metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5UQ--MvACc2umL7amm02W-ZrmnLL0tk
"""

"""
metrics.py
----------
Custom metrics and explainability utilities for HLNN evaluation.

Author: abdullah
Python Version: 3.11
"""

import numpy as np
from sklearn.metrics import f1_score, precision_score, recall_score

def compute_f1(y_true, y_pred):
    return f1_score(y_true, y_pred, average='weighted')

def compute_precision(y_true, y_pred):
    return precision_score(y_true, y_pred, average='weighted')

def compute_recall(y_true, y_pred):
    return recall_score(y_true, y_pred, average='weighted')

def attention_entropy(attention_weights):
    """
    Computes attention entropy: low entropy indicates concentrated focus.
    attention_weights: shape (num_tokens,)
    """
    a = np.array(attention_weights)
    a = a / np.sum(a)
    entropy = -np.sum(a * np.log(a + 1e-8))
    return entropy